### ISSUE TITLE
await till all tasks completed

### ISSUE THREAD

**Issue by gitmalong** [alttch/tokio-task-pool#1]
Maybe the doc is just lacking of this but how does one await the pool until all tasks completed?

Like this?

```rust
loop {
    if let Some(busy) = pool.busy_permits() {
        if busy == 0 {
            break;
        }
    }
    tokio::time::sleep(Duration::from_millis(100)).await;
}
```

**Comment by divi255** [comment]
Good day,

spawn results are regular futures join handles, so you can use any typical method.
